### ISSUE TITLE
In - TypeError: explode(): Argument #2 ($string) must be of type string, array given in file

### ISSUE THREAD

**Issue by ahmet-cetinkaya** [mehradsadeghi/laravel-filter-querystring#18]
`?in[0]=field1,value1,value2&in[1]=field2,value3,value4`

I am getting the following error when I submit a query with the above parameter.

<details>
<summary>Click to toggle error</summary>

<br>

```
TypeError: explode(): Argument #2 ($string) must be of type string, array given in file C:\project\vendor\mehradsadeghi\laravel-filter-querystring\helpers\helpers.php on line 6

#0 C:\project\vendor\mehradsadeghi\laravel-filter-querystring\helpers\helpers.php(6): explode()
#1 C:\project\vendor\mehradsadeghi\laravel-filter-querystring\src\Filters\WhereInClause.php(22): separateCommaValues()
#2 C:\project\vendor\mehradsadeghi\laravel-filter-querystring\src\Filters\BaseClause.php(23): Mehradsadeghi\FilterQueryString\Filters\WhereInClause-&gt;validate()
#3 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Mehradsadeghi\FilterQueryString\Filters\BaseClause-&gt;handle()
#4 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#5 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Pipeline\Pipeline-&gt;then()
#6 C:\project\vendor\mehradsadeghi\laravel-filter-querystring\src\FilterQueryString.php(36): Illuminate\Pipeline\Pipeline-&gt;thenReturn()
#7 C:\project\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1477): App\Models\PathologyReport-&gt;scopeFilter()
#8 C:\project\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(1268): Illuminate\Database\Eloquent\Model-&gt;callNamedScope()
#9 C:\project\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(1249): Illuminate\Database\Eloquent\Builder-&gt;Illuminate\Database\Eloquent\{closure}()
#10 C:\project\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(1267): Illuminate\Database\Eloquent\Builder-&gt;callScope()
#11 C:\project\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(1703): Illuminate\Database\Eloquent\Builder-&gt;callNamedScope()
#12 C:\project\app\Features\PathologyReports\Queries\GetListPathologyReport\GetListPathologyReportQueryHandler.php(14): Illuminate\Database\Eloquent\Builder-&gt;__call()
#13 [internal function]: App\Features\PathologyReports\Queries\GetListPathologyReport\GetListPathologyReportQueryHandler-&gt;Handle()
#14 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Processor\MethodInvoker\MethodInvoker.php(232): call_user_func_array()
#15 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Processor\WrapWithMessageBuildProcessor.php(48): Ecotone\Messaging\Handler\Processor\MethodInvoker\MethodInvoker-&gt;processMessage()
#16 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\RequestReplyProducer.php(87): Ecotone\Messaging\Handler\Processor\WrapWithMessageBuildProcessor-&gt;processMessage()
#17 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\ServiceActivator\ServiceActivatingHandler.php(35): Ecotone\Messaging\Handler\RequestReplyProducer-&gt;handleWithReply()
#18 C:\project\vendor\ecotone\ecotone\src\Messaging\Endpoint\EventDriven\LazyMessageHandler.php(36): Ecotone\Messaging\Handler\ServiceActivator\ServiceActivatingHandler-&gt;handle()
#19 C:\project\vendor\ecotone\ecotone\src\Messaging\Channel\DirectChannel.php(43): Ecotone\Messaging\Endpoint\EventDriven\LazyMessageHandler-&gt;handle()
#20 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\RequestReplyProducer.php(135): Ecotone\Messaging\Channel\DirectChannel-&gt;send()
#21 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\ServiceActivator\ServiceActivatingHandler.php(35): Ecotone\Messaging\Handler\RequestReplyProducer-&gt;handleWithReply()
#22 C:\project\vendor\ecotone\ecotone\src\Messaging\Endpoint\EventDriven\LazyMessageHandler.php(36): Ecotone\Messaging\Handler\ServiceActivator\ServiceActivatingHandler-&gt;handle()
#23 C:\project\vendor\ecotone\ecotone\src\Messaging\Channel\PublishSubscribeChannel.php(40): Ecotone\Messaging\Endpoint\EventDriven\LazyMessageHandler-&gt;handle()
#24 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Router\Router.php(98): Ecotone\Messaging\Channel\PublishSubscribeChannel-&gt;send()
#25 C:\project\vendor\ecotone\ecotone\src\Messaging\Endpoint\EventDriven\LazyMessageHandler.php(36): Ecotone\Messaging\Handler\Router\Router-&gt;handle()
#26 C:\project\vendor\ecotone\ecotone\src\Messaging\Channel\DirectChannel.php(43): Ecotone\Messaging\Endpoint\EventDriven\LazyMessageHandler-&gt;handle()
#27 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Gateway\GatewayInternalHandler.php(70): Ecotone\Messaging\Channel\DirectChannel-&gt;send()
#28 [internal function]: Ecotone\Messaging\Handler\Gateway\GatewayInternalHandler-&gt;handle()
#29 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Processor\MethodInvoker\MethodInvokerChainProcessor.php(59): call_user_func_array()
#30 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Gateway\ConversionInterceptor.php(32): Ecotone\Messaging\Handler\Processor\MethodInvoker\MethodInvokerChainProcessor-&gt;proceed()
#31 [internal function]: Ecotone\Messaging\Handler\Gateway\ConversionInterceptor-&gt;convert()
#32 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Processor\MethodInvoker\AroundMethodInterceptor.php(140): call_user_func_array()
#33 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Processor\MethodInvoker\MethodInvokerChainProcessor.php(65): Ecotone\Messaging\Handler\Processor\MethodInvoker\AroundMethodInterceptor-&gt;invoke()
#34 C:\project\vendor\ecotone\ecotone\src\Modelling\MessageHandling\MetadataPropagator\MessageHeadersPropagator.php(29): Ecotone\Messaging\Handler\Processor\MethodInvoker\MethodInvokerChainProcessor-&gt;proceed()
#35 [internal function]: Ecotone\Modelling\MessageHandling\MetadataPropagator\MessageHeadersPropagator-&gt;storeHeaders()
#36 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Processor\MethodInvoker\AroundMethodInterceptor.php(140): call_user_func_array()
#37 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Processor\MethodInvoker\MethodInvokerChainProcessor.php(65): Ecotone\Messaging\Handler\Processor\MethodInvoker\AroundMethodInterceptor-&gt;invoke()
#38 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Processor\MethodInvoker\MethodInvoker.php(245): Ecotone\Messaging\Handler\Processor\MethodInvoker\MethodInvokerChainProcessor-&gt;proceed()
#39 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\RequestReplyProducer.php(87): Ecotone\Messaging\Handler\Processor\MethodInvoker\MethodInvoker-&gt;processMessage()
#40 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\ServiceActivator\ServiceActivatingHandler.php(35): Ecotone\Messaging\Handler\RequestReplyProducer-&gt;handleWithReply()
#41 C:\project\vendor\ecotone\ecotone\src\Messaging\Channel\DirectChannel.php(43): Ecotone\Messaging\Handler\ServiceActivator\ServiceActivatingHandler-&gt;handle()
#42 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\RequestReplyProducer.php(135): Ecotone\Messaging\Channel\DirectChannel-&gt;send()
#43 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Transformer\Transformer.php(32): Ecotone\Messaging\Handler\RequestReplyProducer-&gt;handleWithReply()
#44 C:\project\vendor\ecotone\ecotone\src\Messaging\Channel\DirectChannel.php(43): Ecotone\Messaging\Handler\Transformer\Transformer-&gt;handle()
#45 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Chain\ChainForwardPublisher.php(46): Ecotone\Messaging\Channel\DirectChannel-&gt;send()
#46 [internal function]: Ecotone\Messaging\Handler\Chain\ChainForwardPublisher-&gt;forward()
#47 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Processor\MethodInvoker\MethodInvoker.php(232): call_user_func_array()
#48 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Processor\WrapWithMessageBuildProcessor.php(48): Ecotone\Messaging\Handler\Processor\MethodInvoker\MethodInvoker-&gt;processMessage()
#49 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\RequestReplyProducer.php(87): Ecotone\Messaging\Handler\Processor\WrapWithMessageBuildProcessor-&gt;processMessage()
#50 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\ServiceActivator\ServiceActivatingHandler.php(35): Ecotone\Messaging\Handler\RequestReplyProducer-&gt;handleWithReply()
#51 C:\project\vendor\ecotone\ecotone\src\Messaging\Handler\Gateway\Gateway.php(162): Ecotone\Messaging\Handler\ServiceActivator\ServiceActivatingHandler-&gt;handle()
#52 C:\project\vendor\ecotone\ecotone\src\Messaging\Config\NonProxyCombinedGateway.php(59): Ecotone\Messaging\Handler\Gateway\Gateway-&gt;execute()
#53 C:\project\vendor\ecotone\laravel\src\Laravel\ProxyGenerator.php(52): Ecotone\Messaging\Config\NonProxyCombinedGateway-&gt;executeMethod()
#54 C:\project\vendor\friendsofphp\proxy-manager-lts\src\ProxyManager\GeneratorStrategy\EvaluatingGeneratorStrategy.php(54) : eval()&#039;d code(26): ProxyManager\Factory\RemoteObject\AdapterInterface@anonymous-&gt;call()
#55 C:\project\app\Http\Controllers\PathologyReportController.php(31): ProxyManagerGeneratedProxy\__PM__\Ecotone\Modelling\QueryBus\Generated41e85252773487a13a49c9d468e64480-&gt;send()
#56 C:\project\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\PathologyReportController-&gt;getList()
#57 C:\project\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller-&gt;callAction()
#58 C:\project\vendor\laravel\framework\src\Illuminate\Routing\Route.php(261): Illuminate\Routing\ControllerDispatcher-&gt;dispatch()
#59 C:\project\vendor\laravel\framework\src\Illuminate\Routing\Route.php(204): Illuminate\Routing\Route-&gt;runController()
#60 C:\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php(725): Illuminate\Routing\Route-&gt;run()
#61 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}()
#62 C:\project\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#63 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle()
#64 C:\project\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(126): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#65 C:\project\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(102): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handleRequest()
#66 C:\project\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(54): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handleRequestUsingNamedLimiter()
#67 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handle()
#68 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#69 C:\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php(727): Illuminate\Pipeline\Pipeline-&gt;then()
#70 C:\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php(702): Illuminate\Routing\Router-&gt;runRouteWithinStack()
#71 C:\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php(666): Illuminate\Routing\Router-&gt;runRoute()
#72 C:\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php(655): Illuminate\Routing\Router-&gt;dispatchToRoute()
#73 C:\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router-&gt;dispatch()
#74 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}()
#75 C:\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#76 C:\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle()
#77 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull-&gt;handle()
#78 C:\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#79 C:\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle()
#80 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings-&gt;handle()
#81 C:\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#82 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle()
#83 C:\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#84 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle()
#85 C:\project\vendor\laravel\framework\src\Illuminate\Http\Middleware\HandleCors.php(62): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#86 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Http\Middleware\HandleCors-&gt;handle()
#87 C:\project\vendor\laravel\framework\src\Illuminate\Http\Middleware\TrustProxies.php(39): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#88 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies-&gt;handle()
#89 C:\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#90 C:\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline-&gt;then()
#91 C:\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter()
#92 C:\project\public\index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle()
#93 C:\project\vendor\laravel\framework\src\Illuminate\Foundation\resources\server.php(16): require_once(&#039;...&#039;)
#94 {main}
```
</details>

**Comment by mehradsadeghi** [comment]
Yeah. the `in` filter doesn't accept array in current version.
